services:
    ckfinder.connector.auth:
        class: '%ckfinder.connector.auth.class%'
        public: true
        calls:
            - [setContainer, ['@service_container']]

    ckfinder.connector.factory:
        class: '%ckfinder.connector.factory.class%'
        public: true
        arguments: ['%ckfinder.connector.config%', '@ckfinder.connector.auth', null]

    ckfinder.connector:
        class: '%ckfinder.connector.class%'
        factory: ['@ckfinder.connector.factory', 'getConnector']
        public: true

    ckfinder.command.download:
        class: CKSource\Bundle\CKFinderBundle\Command\CKFinderDownloadCommand
        arguments:
            $patcher: '@CKSource\Bundle\CKFinderBundle\Patcher\ChainedPatcher'
        tags:
            - { name: console.command }

    # Patchers
    CKSource\Bundle\CKFinderBundle\Patcher\ChainedPatcher:
        arguments:
            $patchers: !tagged_iterator { tag: ckfinder.patcher }

    CKSource\Bundle\CKFinderBundle\Patcher\ScopedDependenciesPatcher:
        tags:
            - { name: ckfinder.patcher, priority: 150 }

    CKSource\Bundle\CKFinderBundle\Patcher\Symfony54Patcher:
        tags:
            - { name: ckfinder.patcher, priority: 100 }

    CKSource\Bundle\CKFinderBundle\Patcher\BackendAwsS3ClientPatcher:
        tags:
            - { name: ckfinder.patcher, priority: 100 }
